server:
  port: 80


spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/userservice
    username: root
    password: Lndixit@107
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
